name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    # https://github.com/frewsxcv/cargo-all-features
    steps:
    - uses: actions/checkout@v4
    - run: cargo install cargo-all-features
    - name: Build
    - run: cargo build-all-features release
    - name: Test
    - run: cargo test-all-features

    
